DATA = {
    "ASTONISH": "to surprise someone in a big way",
    "ELOQUENT": "speaking in a very smooth and powerful way",
    "FASCINATE": "to make someone very interested",
    "INTRICATE": "having many small and detailed parts",
    "JUBILANT": "feeling extremely happy and excited",
    "KINDRED": "feeling deeply connected, like family",
    "LUMINOUS": "shining brightly in the dark",
    "MELANCHONY": "a deep and quiet kind of sadness",
    "NOTORIOUS": "famous, but for something bad",
    "PONDER": "to think deeply about something",
    "QUAINT": "old-fashioned but in a charming way",
    "RECKLESS": "taking big risks without thinking",
    "SOLACE": "feeling comfort during sad time",
    "TRANQUIL": "very calm and peaceful",
    "UNRAVEL": "to figure out or solve something confusing",
    "VENGEANCE": "hurting someone back for what they did",
    "WHIMSICAL": "playful, fun, and a little unusual",
    "YEARN": "to really want something badly",
    "ZEALOUS": "very excited and passionate about something",
    "ADORN": "to decorate or make something more beautiful",
    "BROOD": "to keep thinking about something in a sad way",
    "CONCEAL": "to hide something from others",
    "DEVOUR": "to eat something very quickly and hungrily",
    "ENGULF": "to completely surround or cover something",
    "SCURRY": "to run quickly",
    "PERPLEXED": "very confused",
    "ZENITH": "the highest or most successful point",
    "MERAKI": "to do something with soul, creativity, or love",
    "KAIROS": "the perfect, right, or opportune moment",
    "HIRAETH": "a deep longing for something lost or unattainable",
    }
a = input ("SAY 'ANO KAILANGAN NG BABAE NA YAN' ")
print (DATA[a])